pipeline {
    agent any
    
    stages {
        stage('Checkout') {
            steps {
                // Checkout code from GitHub repository
                git 'https://github.com/haniyatj/simple-reactjs-app-master'
            }
        }
        
        stage('Dependency Installation') {
            steps {
                // Install Node.js dependencies using npm
                sh 'npm install'
            }
        }
        
        stage('Build Docker Image') {
            steps {
                // Build Docker image using Dockerfile
                sh 'docker build -t emily .'
            }
        }
        
        stage('Run Docker Image') {
            steps {
                // Run Docker container from the built image
                sh 'docker run -d -p 8080:8080 emily'
            }
        }
        
        stage('Push Docker Image') {
            steps {
                withDockerRegistry([credentialsId: '3dad1a07-5720-4c90-8611-b549a64ae36b', url: 'https://index.docker.io/v1/']) {
                    // Push Docker image to Docker Hub
                    sh 'docker push emily'
                }
            }
        }
    }
}
